import "./globals.css";
import ReactQuery from "../components/ReactQuery";
import Recoil from "../components/Recoil";
import ReactHotToast from "../components/ReactHotToast";

export const metadata = {
  title: "Ducky Dev - HARAHO",
  description:
    "Generated by create next app. This Page is Ducky Dev HARAHO's Portfolio",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <Recoil>
          <ReactQuery>
            <header>
              <h1>HEADER TEST</h1>
            </header>
            {children}
            <footer>
              <h1>FOOTER TEST</h1>
            </footer>
          </ReactQuery>
        </Recoil>
        <ReactHotToast />
      </body>
    </html>
  );
}
